package com.am.entity;
// Generated 20 nov. 2018 18:53:33 by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Tfunction generated by hbm2java
 */
@Entity
@Table(name = "tfunction2", catalog = "projectmanagement")
public class Tfunction implements java.io.Serializable {

	private int idfunction;
	private String namefunction;
	private String progfunction;
	private int enabledfunction;
	@JsonIgnore
	private Set<Trolefunction> trolefunctions = new HashSet<Trolefunction>(0);

	public Tfunction() {
	}

	public Tfunction(int idfunction, String namefunction, int enabledfunction) {
		this.idfunction = idfunction;
		this.namefunction = namefunction;
		this.enabledfunction = enabledfunction;
	}

	public Tfunction(int idfunction, String namefunction, String progfunction, int enabledfunction,
			Set<Trolefunction> trolefunctions) {
		this.idfunction = idfunction;
		this.namefunction = namefunction;
		this.progfunction = progfunction;
		this.enabledfunction = enabledfunction;
		this.trolefunctions = trolefunctions;
	}

	@Id

	@Column(name = "idfunction", unique = true, nullable = false)
	public int getIdfunction() {
		return this.idfunction;
	}

	public void setIdfunction(int idfunction) {
		this.idfunction = idfunction;
	}

	@Column(name = "namefunction", nullable = false, length = 30)
	public String getNamefunction() {
		return this.namefunction;
	}

	public void setNamefunction(String namefunction) {
		this.namefunction = namefunction;
	}

	@Column(name = "progfunction", length = 60)
	public String getProgfunction() {
		return this.progfunction;
	}

	public void setProgfunction(String progfunction) {
		this.progfunction = progfunction;
	}

	@Column(name = "enabledfunction", nullable = false)
	public int getEnabledfunction() {
		return this.enabledfunction;
	}

	public void setEnabledfunction(int enabledfunction) {
		this.enabledfunction = enabledfunction;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tfunction")
	public Set<Trolefunction> getTrolefunctions() {
		return this.trolefunctions;
	}

	public void setTrolefunctions(Set<Trolefunction> trolefunctions) {
		this.trolefunctions = trolefunctions;
	}

}
