// default package
// Generated 11 nov. 2018 20:55:22 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tperson generated by hbm2java
 */
@Entity
@Table(name="tperson"
    ,catalog="projectmanagement"
)
public class Tperson  implements java.io.Serializable {


     private int idperson;
     private String nameperson;
     private String emailperson;
     private Set treporters = new HashSet(0);

    public Tperson() {
    }

	
    public Tperson(int idperson) {
        this.idperson = idperson;
    }
    public Tperson(int idperson, String nameperson, String emailperson, Set treporters) {
       this.idperson = idperson;
       this.nameperson = nameperson;
       this.emailperson = emailperson;
       this.treporters = treporters;
    }
   
     @Id 

    
    @Column(name="idperson", unique=true, nullable=false)
    public int getIdperson() {
        return this.idperson;
    }
    
    public void setIdperson(int idperson) {
        this.idperson = idperson;
    }

    
    @Column(name="nameperson", length=60)
    public String getNameperson() {
        return this.nameperson;
    }
    
    public void setNameperson(String nameperson) {
        this.nameperson = nameperson;
    }

    
    @Column(name="emailperson", length=60)
    public String getEmailperson() {
        return this.emailperson;
    }
    
    public void setEmailperson(String emailperson) {
        this.emailperson = emailperson;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tperson")
    public Set getTreporters() {
        return this.treporters;
    }
    
    public void setTreporters(Set treporters) {
        this.treporters = treporters;
    }




}


