package com.am.entity;
// Generated 20 nov. 2018 18:53:33 by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Tperson generated by hbm2java
 */
@Entity
@Table(name = "tperson", catalog = "projectmanagement")
public class Tperson implements java.io.Serializable {

	private Long idperson;
	private String nameperson;
	private String emailperson;
	@JsonIgnore
	private Set<Treporter> treporters = new HashSet<Treporter>(0);
	@JsonIgnore
	private Set<Tuser> tusers = new HashSet<Tuser>(0);

	public Tperson() {
	}

	public Tperson(Long idperson) {
		this.idperson = idperson;
	}

	public Tperson(Long idperson, String nameperson, String emailperson, Set<Treporter> treporters, Set<Tuser> tusers) {
		this.idperson = idperson;
		this.nameperson = nameperson;
		this.emailperson = emailperson;
		this.treporters = treporters;
		this.tusers = tusers;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	/*@GeneratedValue(strategy=GenerationType.TABLE , generator="employee_generator")
	@TableGenerator(name="employee_generator", 
	                table="pk_table", 
	                pkColumnName="name", 
	                valueColumnName="value",                            
	                allocationSize=100)*/ 
	@Column(name = "idperson", unique = true, nullable = false)
	public Long getIdperson() {
		return this.idperson;
	}

	public void setIdperson(Long idperson) {
		this.idperson = idperson;
	}

	@Column(name = "nameperson", length = 60)
	public String getNameperson() {
		return this.nameperson;
	}

	public void setNameperson(String nameperson) {
		this.nameperson = nameperson;
	}

	@Column(name = "emailperson", length = 60)
	public String getEmailperson() {
		return this.emailperson;
	}

	public void setEmailperson(String emailperson) {
		this.emailperson = emailperson;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tperson",cascade=CascadeType.PERSIST)
	@JsonIgnore
	public Set<Treporter> getTreporters() {
		return this.treporters;
	}

	public void setTreporters(Set<Treporter> treporters) {
		this.treporters = treporters;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tperson",cascade=CascadeType.PERSIST)
	@JsonIgnore
	public Set<Tuser> getTusers() {
		return this.tusers;
	}

	public void setTusers(Set<Tuser> tusers) {
		this.tusers = tusers;
	}

}
