package com.am.entity;
// Generated 20 nov. 2018 18:53:33 by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Tproduct generated by hbm2java
 */
@Entity
@Table(name = "tproduct", catalog = "projectmanagement")
public class Tproduct implements java.io.Serializable {

	private int idproduct;
	private String nameproduct;
	private Integer enabledproduct;
	@JsonIgnore
	private Set<Tticket> ttickets = new HashSet<Tticket>(0);

	public Tproduct() {
	}

	public Tproduct(int idproduct) {
		this.idproduct = idproduct;
	}

	public Tproduct(int idproduct, String nameproduct, Integer enabledproduct, Set<Tticket> ttickets) {
		this.idproduct = idproduct;
		this.nameproduct = nameproduct;
		this.enabledproduct = enabledproduct;
		this.ttickets = ttickets;
	}

	@Id

	@Column(name = "idproduct", unique = true, nullable = false)
	public int getIdproduct() {
		return this.idproduct;
	}

	public void setIdproduct(int idproduct) {
		this.idproduct = idproduct;
	}

	@Column(name = "nameproduct", length = 30)
	public String getNameproduct() {
		return this.nameproduct;
	}

	public void setNameproduct(String nameproduct) {
		this.nameproduct = nameproduct;
	}

	@Column(name = "enabledproduct")
	public Integer getEnabledproduct() {
		return this.enabledproduct;
	}

	public void setEnabledproduct(Integer enabledproduct) {
		this.enabledproduct = enabledproduct;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tproduct")
	public Set<Tticket> getTtickets() {
		return this.ttickets;
	}

	public void setTtickets(Set<Tticket> ttickets) {
		this.ttickets = ttickets;
	}

}
