// default package
// Generated 11 nov. 2018 20:55:22 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Treporter generated by hbm2java
 */
@Entity
@Table(name="treporter"
    ,catalog="projectmanagement"
)
public class Treporter  implements java.io.Serializable {


     private int idtreporter;
     private Tperson tperson;
     private int enableduser;
     private int isinternal;

    public Treporter() {
    }

    public Treporter(int idtreporter, Tperson tperson, int enableduser, int isinternal) {
       this.idtreporter = idtreporter;
       this.tperson = tperson;
       this.enableduser = enableduser;
       this.isinternal = isinternal;
    }
   
     @Id 

    
    @Column(name="idtreporter", unique=true, nullable=false)
    public int getIdtreporter() {
        return this.idtreporter;
    }
    
    public void setIdtreporter(int idtreporter) {
        this.idtreporter = idtreporter;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idperson", nullable=false)
    public Tperson getTperson() {
        return this.tperson;
    }
    
    public void setTperson(Tperson tperson) {
        this.tperson = tperson;
    }

    
    @Column(name="enableduser", nullable=false)
    public int getEnableduser() {
        return this.enableduser;
    }
    
    public void setEnableduser(int enableduser) {
        this.enableduser = enableduser;
    }

    
    @Column(name="isinternal", nullable=false)
    public int getIsinternal() {
        return this.isinternal;
    }
    
    public void setIsinternal(int isinternal) {
        this.isinternal = isinternal;
    }




}


