// default package
// Generated 11 nov. 2018 20:55:22 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tresolutionticket generated by hbm2java
 */
@Entity
@Table(name="tresolutionticket"
    ,catalog="projectmanagement"
)
public class Tresolutionticket  implements java.io.Serializable {


     private int idresolution;
     private String nameresolution;
     private Integer enabledresolution;

    public Tresolutionticket() {
    }

	
    public Tresolutionticket(int idresolution) {
        this.idresolution = idresolution;
    }
    public Tresolutionticket(int idresolution, String nameresolution, Integer enabledresolution) {
       this.idresolution = idresolution;
       this.nameresolution = nameresolution;
       this.enabledresolution = enabledresolution;
    }
   
     @Id 

    
    @Column(name="idresolution", unique=true, nullable=false)
    public int getIdresolution() {
        return this.idresolution;
    }
    
    public void setIdresolution(int idresolution) {
        this.idresolution = idresolution;
    }

    
    @Column(name="nameresolution", length=30)
    public String getNameresolution() {
        return this.nameresolution;
    }
    
    public void setNameresolution(String nameresolution) {
        this.nameresolution = nameresolution;
    }

    
    @Column(name="enabledresolution")
    public Integer getEnabledresolution() {
        return this.enabledresolution;
    }
    
    public void setEnabledresolution(Integer enabledresolution) {
        this.enabledresolution = enabledresolution;
    }




}


