// default package
// Generated 11 nov. 2018 20:55:22 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TroleId generated by hbm2java
 */
@Embeddable
public class TroleId  implements java.io.Serializable {


     private int idrole;
     private String namerole;
     private int enabledrole;
     private String descrole;

    public TroleId() {
    }

	
    public TroleId(int idrole, String namerole, int enabledrole) {
        this.idrole = idrole;
        this.namerole = namerole;
        this.enabledrole = enabledrole;
    }
    public TroleId(int idrole, String namerole, int enabledrole, String descrole) {
       this.idrole = idrole;
       this.namerole = namerole;
       this.enabledrole = enabledrole;
       this.descrole = descrole;
    }
   


    @Column(name="idrole", nullable=false)
    public int getIdrole() {
        return this.idrole;
    }
    
    public void setIdrole(int idrole) {
        this.idrole = idrole;
    }


    @Column(name="namerole", nullable=false, length=30)
    public String getNamerole() {
        return this.namerole;
    }
    
    public void setNamerole(String namerole) {
        this.namerole = namerole;
    }


    @Column(name="enabledrole", nullable=false)
    public int getEnabledrole() {
        return this.enabledrole;
    }
    
    public void setEnabledrole(int enabledrole) {
        this.enabledrole = enabledrole;
    }


    @Column(name="descrole", length=120)
    public String getDescrole() {
        return this.descrole;
    }
    
    public void setDescrole(String descrole) {
        this.descrole = descrole;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TroleId) ) return false;
		 TroleId castOther = ( TroleId ) other; 
         
		 return (this.getIdrole()==castOther.getIdrole())
 && ( (this.getNamerole()==castOther.getNamerole()) || ( this.getNamerole()!=null && castOther.getNamerole()!=null && this.getNamerole().equals(castOther.getNamerole()) ) )
 && (this.getEnabledrole()==castOther.getEnabledrole())
 && ( (this.getDescrole()==castOther.getDescrole()) || ( this.getDescrole()!=null && castOther.getDescrole()!=null && this.getDescrole().equals(castOther.getDescrole()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdrole();
         result = 37 * result + ( getNamerole() == null ? 0 : this.getNamerole().hashCode() );
         result = 37 * result + this.getEnabledrole();
         result = 37 * result + ( getDescrole() == null ? 0 : this.getDescrole().hashCode() );
         return result;
   }   


}


