package com.am.entity;
// Generated 20 nov. 2018 18:53:33 by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Troleview generated by hbm2java
 */
@Entity
@Table(name = "troleview", catalog = "projectmanagement")
public class Troleview implements java.io.Serializable {

	private Long idroleview;
	private Tview tview;
	private Trole trole;
	private Integer cview;
	private Integer rview;
	private Integer uview;
	private Integer dview;

	public Troleview() {
	}

	public Troleview(Long idroleview, Tview tview, Trole trole, Integer cview, Integer rview,
			Integer uview, Integer dview) {
		this.idroleview = idroleview;
		this.tview = tview;
		this.trole = trole;
		this.cview = cview;
		this.rview = rview;
		this.uview = uview;
		this.dview = dview;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "idroleview", unique = true, nullable = false)
	public Long getIdroleview() {
		return this.idroleview;
	}

	public void setIdroleview(Long idroleview) {
		this.idroleview = idroleview;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idview", nullable = false)
	public Tview getTview() {
		return this.tview;
	}

	public void setTview(Tview tview) {
		this.tview = tview;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idrole", nullable = false)
	public Trole getTrole() {
		return this.trole;
	}

	public void setTrole(Trole trole) {
		this.trole = trole;
	}

	@Column(name = "cview", nullable = false)
	public Integer getCview() {
		return this.cview;
	}

	public void setCview(Integer cview) {
		this.cview = cview;
	}

	@Column(name = "rview", nullable = false)
	public Integer getRview() {
		return this.rview;
	}

	public void setRview(Integer rview) {
		this.rview = rview;
	}

	@Column(name = "uview", nullable = false)
	public Integer getUview() {
		return this.uview;
	}

	public void setUview(Integer uview) {
		this.uview = uview;
	}

	@Column(name = "dview", nullable = false)
	public Integer getDview() {
		return this.dview;
	}

	public void setDview(Integer dview) {
		this.dview = dview;
	}

}
