package com.am.entity;
// Generated 20 nov. 2018 18:53:33 by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Troleview generated by hbm2java
 */
@Entity
@Table(name = "troleview", catalog = "projectmanagement")
public class Troleview implements java.io.Serializable {

	private int idroleview;
	private Tview tview;
	private Trole trole;
	private int cview;
	private int rview;
	private int uview;
	private int dview;

	public Troleview() {
	}

	public Troleview(int idroleview, Tview tview, Trole trole, int cview, int rview,
			int uview, int dview) {
		this.idroleview = idroleview;
		this.tview = tview;
		this.trole = trole;
		this.cview = cview;
		this.rview = rview;
		this.uview = uview;
		this.dview = dview;
	}

	@Id

	@Column(name = "idroleview", unique = true, nullable = false)
	public int getIdroleview() {
		return this.idroleview;
	}

	public void setIdroleview(int idroleview) {
		this.idroleview = idroleview;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idview", nullable = false)
	public Tview getTview() {
		return this.tview;
	}

	public void setTview(Tview tview) {
		this.tview = tview;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idrole", nullable = false)
	public Trole getTrole() {
		return this.trole;
	}

	public void setTrole(Trole trole) {
		this.trole = trole;
	}

	@Column(name = "cview", nullable = false)
	public int getCview() {
		return this.cview;
	}

	public void setCview(int cview) {
		this.cview = cview;
	}

	@Column(name = "rview", nullable = false)
	public int getRview() {
		return this.rview;
	}

	public void setRview(int rview) {
		this.rview = rview;
	}

	@Column(name = "uview", nullable = false)
	public int getUview() {
		return this.uview;
	}

	public void setUview(int uview) {
		this.uview = uview;
	}

	@Column(name = "dview", nullable = false)
	public int getDview() {
		return this.dview;
	}

	public void setDview(int dview) {
		this.dview = dview;
	}

}
