// default package
// Generated 11 nov. 2018 20:55:22 by Hibernate Tools 3.4.0.CR1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Trole generated by hbm2java
 */
@Entity
@Table(name="trole"
    ,catalog="projectmanagement"
)
public class Trole  implements java.io.Serializable {


     private TroleId id;

    public Trole() {
    }

    public Trole(TroleId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idrole", column=@Column(name="idrole", nullable=false) ), 
        @AttributeOverride(name="namerole", column=@Column(name="namerole", nullable=false, length=30) ), 
        @AttributeOverride(name="enabledrole", column=@Column(name="enabledrole", nullable=false) ), 
        @AttributeOverride(name="descrole", column=@Column(name="descrole", length=120) ) } )
    public TroleId getId() {
        return this.id;
    }
    
    public void setId(TroleId id) {
        this.id = id;
    }




}


