// default package
// Generated 11 nov. 2018 20:55:22 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tstatusticket generated by hbm2java
 */
@Entity
@Table(name="tstatusticket"
    ,catalog="projectmanagement"
)
public class Tstatusticket  implements java.io.Serializable {


     private int idstatusticket;
     private String namestatus;
     private Integer enabledstatus;

    public Tstatusticket() {
    }

	
    public Tstatusticket(int idstatusticket) {
        this.idstatusticket = idstatusticket;
    }
    public Tstatusticket(int idstatusticket, String namestatus, Integer enabledstatus) {
       this.idstatusticket = idstatusticket;
       this.namestatus = namestatus;
       this.enabledstatus = enabledstatus;
    }
   
     @Id 

    
    @Column(name="idstatusticket", unique=true, nullable=false)
    public int getIdstatusticket() {
        return this.idstatusticket;
    }
    
    public void setIdstatusticket(int idstatusticket) {
        this.idstatusticket = idstatusticket;
    }

    
    @Column(name="namestatus", length=30)
    public String getNamestatus() {
        return this.namestatus;
    }
    
    public void setNamestatus(String namestatus) {
        this.namestatus = namestatus;
    }

    
    @Column(name="enabledstatus")
    public Integer getEnabledstatus() {
        return this.enabledstatus;
    }
    
    public void setEnabledstatus(Integer enabledstatus) {
        this.enabledstatus = enabledstatus;
    }




}


