package com.am.entity;
// Generated 20 nov. 2018 18:53:33 by Hibernate Tools 5.1.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Tticket generated by hbm2java
 */
@Entity
@Table(name = "tticket", catalog = "projectmanagement")
public class Tticket implements java.io.Serializable {

	private int idticket;
	private Tproduct tproduct;
	private Tproductversion tproductversion;
	private Treporter treporter;
	private Tvocabword tvocabwordByVocticketstatus;
	private Tvocabword tvocabwordByVocticketresol;
	private Date dateticket;
	private String externalcodea;
	private String summary;
	@JsonIgnore
	private Set<Ttickoprodversresol> ttickoprodversresols = new HashSet<Ttickoprodversresol>(0);

	public Tticket() {
	}

	public Tticket(int idticket, Tproduct tproduct, Tproductversion tproductversion, Treporter treporter,
			Tvocabword tvocabwordByVocticketstatus, Tvocabword tvocabwordByVocticketresol, Date dateticket) {
		this.idticket = idticket;
		this.tproduct = tproduct;
		this.tproductversion = tproductversion;
		this.treporter = treporter;
		this.tvocabwordByVocticketstatus = tvocabwordByVocticketstatus;
		this.tvocabwordByVocticketresol = tvocabwordByVocticketresol;
		this.dateticket = dateticket;
	}

	public Tticket(int idticket, Tproduct tproduct, Tproductversion tproductversion, Treporter treporter,
			Tvocabword tvocabwordByVocticketstatus, Tvocabword tvocabwordByVocticketresol, Date dateticket,
			String externalcodea, String summary, Set<Ttickoprodversresol> ttickoprodversresols) {
		this.idticket = idticket;
		this.tproduct = tproduct;
		this.tproductversion = tproductversion;
		this.treporter = treporter;
		this.tvocabwordByVocticketstatus = tvocabwordByVocticketstatus;
		this.tvocabwordByVocticketresol = tvocabwordByVocticketresol;
		this.dateticket = dateticket;
		this.externalcodea = externalcodea;
		this.summary = summary;
		this.ttickoprodversresols = ttickoprodversresols;
	}

	@Id

	@Column(name = "idticket", unique = true, nullable = false)
	public int getIdticket() {
		return this.idticket;
	}

	public void setIdticket(int idticket) {
		this.idticket = idticket;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idproduct", nullable = false)
	public Tproduct getTproduct() {
		return this.tproduct;
	}

	public void setTproduct(Tproduct tproduct) {
		this.tproduct = tproduct;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idproductversion", nullable = false)
	public Tproductversion getTproductversion() {
		return this.tproductversion;
	}

	public void setTproductversion(Tproductversion tproductversion) {
		this.tproductversion = tproductversion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idreporter", nullable = false)
	public Treporter getTreporter() {
		return this.treporter;
	}

	public void setTreporter(Treporter treporter) {
		this.treporter = treporter;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "vocticketstatus", nullable = false)
	public Tvocabword getTvocabwordByVocticketstatus() {
		return this.tvocabwordByVocticketstatus;
	}

	public void setTvocabwordByVocticketstatus(Tvocabword tvocabwordByVocticketstatus) {
		this.tvocabwordByVocticketstatus = tvocabwordByVocticketstatus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "vocticketresol", nullable = false)
	public Tvocabword getTvocabwordByVocticketresol() {
		return this.tvocabwordByVocticketresol;
	}

	public void setTvocabwordByVocticketresol(Tvocabword tvocabwordByVocticketresol) {
		this.tvocabwordByVocticketresol = tvocabwordByVocticketresol;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateticket", nullable = false, length = 19)
	public Date getDateticket() {
		return this.dateticket;
	}

	public void setDateticket(Date dateticket) {
		this.dateticket = dateticket;
	}

	@Column(name = "externalcodea", length = 60)
	public String getExternalcodea() {
		return this.externalcodea;
	}

	public void setExternalcodea(String externalcodea) {
		this.externalcodea = externalcodea;
	}

	@Column(name = "summary", length = 60)
	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tticket")
	public Set<Ttickoprodversresol> getTtickoprodversresols() {
		return this.ttickoprodversresols;
	}

	public void setTtickoprodversresols(Set<Ttickoprodversresol> ttickoprodversresols) {
		this.ttickoprodversresols = ttickoprodversresols;
	}

}
