// default package
// Generated 11 nov. 2018 20:55:22 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tticket generated by hbm2java
 */
@Entity
@Table(name="tticket"
    ,catalog="projectmanagement"
)
public class Tticket  implements java.io.Serializable {


     private int idticket;
     private Tticket tticket;
     private Tproduct tproduct;
     private Date subdate;
     private String externalcodea;
     private String summary;
     private Integer idreporter;
     private Integer idversionproduct;
     private Integer idresolution;
     private Set ttickets = new HashSet(0);

    public Tticket() {
    }

	
    public Tticket(int idticket) {
        this.idticket = idticket;
    }
    public Tticket(int idticket, Tticket tticket, Tproduct tproduct, Date subdate, String externalcodea, String summary, Integer idreporter, Integer idversionproduct, Integer idresolution, Set ttickets) {
       this.idticket = idticket;
       this.tticket = tticket;
       this.tproduct = tproduct;
       this.subdate = subdate;
       this.externalcodea = externalcodea;
       this.summary = summary;
       this.idreporter = idreporter;
       this.idversionproduct = idversionproduct;
       this.idresolution = idresolution;
       this.ttickets = ttickets;
    }
   
     @Id 

    
    @Column(name="idticket", unique=true, nullable=false)
    public int getIdticket() {
        return this.idticket;
    }
    
    public void setIdticket(int idticket) {
        this.idticket = idticket;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idstatusticket")
    public Tticket getTticket() {
        return this.tticket;
    }
    
    public void setTticket(Tticket tticket) {
        this.tticket = tticket;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idproduct")
    public Tproduct getTproduct() {
        return this.tproduct;
    }
    
    public void setTproduct(Tproduct tproduct) {
        this.tproduct = tproduct;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="subdate", length=0)
    public Date getSubdate() {
        return this.subdate;
    }
    
    public void setSubdate(Date subdate) {
        this.subdate = subdate;
    }

    
    @Column(name="externalcodea", length=60)
    public String getExternalcodea() {
        return this.externalcodea;
    }
    
    public void setExternalcodea(String externalcodea) {
        this.externalcodea = externalcodea;
    }

    
    @Column(name="summary", length=60)
    public String getSummary() {
        return this.summary;
    }
    
    public void setSummary(String summary) {
        this.summary = summary;
    }

    
    @Column(name="idreporter")
    public Integer getIdreporter() {
        return this.idreporter;
    }
    
    public void setIdreporter(Integer idreporter) {
        this.idreporter = idreporter;
    }

    
    @Column(name="idversionproduct")
    public Integer getIdversionproduct() {
        return this.idversionproduct;
    }
    
    public void setIdversionproduct(Integer idversionproduct) {
        this.idversionproduct = idversionproduct;
    }

    
    @Column(name="idresolution")
    public Integer getIdresolution() {
        return this.idresolution;
    }
    
    public void setIdresolution(Integer idresolution) {
        this.idresolution = idresolution;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tticket")
    public Set getTtickets() {
        return this.ttickets;
    }
    
    public void setTtickets(Set ttickets) {
        this.ttickets = ttickets;
    }




}


