package com.am.entity;
// Generated 20 nov. 2018 18:53:33 by Hibernate Tools 5.1.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Tticket generated by hbm2java
 */
@Entity
@Table(name = "tticket", catalog = "projectmanagement")
public class Tticket implements java.io.Serializable {

	private Long idticket;
	private Tproduct tproduct;
	private Tproductversion tproductversion;
	private Treporter treporter;
	private Tvocabword vocticketstatus;
	private Tvocabword vocticketresol;
	private Date dateticket;
	private String externalcodea;
	private String summary;
	private Set<Ttickoprodversresol> ttickoprodversresols = new HashSet<Ttickoprodversresol>(0);

	public Tticket() {
	}

	public Tticket(Long idticket, Tproduct tproduct, Tproductversion tproductversion, Treporter treporter,
			Tvocabword vocticketstatus, Tvocabword vocticketresol, Date dateticket) {
		this.idticket = idticket;
		this.tproduct = tproduct;
		this.tproductversion = tproductversion;
		this.treporter = treporter;
		this.vocticketstatus = vocticketstatus;
		this.vocticketresol = vocticketresol;
		this.dateticket = dateticket;
	}

	public Tticket(Long idticket, Tproduct tproduct, Tproductversion tproductversion, Treporter treporter,
			Tvocabword vocticketstatus, Tvocabword vocticketresol, Date dateticket,
			String externalcodea, String summary, Set<Ttickoprodversresol> ttickoprodversresols) {
		this.idticket = idticket;
		this.tproduct = tproduct;
		this.tproductversion = tproductversion;
		this.treporter = treporter;
		this.vocticketstatus = vocticketstatus;
		this.vocticketresol = vocticketresol;
		this.dateticket = dateticket;
		this.externalcodea = externalcodea;
		this.summary = summary;
		this.ttickoprodversresols = ttickoprodversresols;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "idticket", unique = true, nullable = false)
	public Long getIdticket() {
		return this.idticket;
	}

	public void setIdticket(Long idticket) {
		this.idticket = idticket;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idproduct", nullable = false)
	@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
	public Tproduct getTproduct() {
		return this.tproduct;
	}

	public void setTproduct(Tproduct tproduct) {
		this.tproduct = tproduct;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idproductversion", nullable = false)
	@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
	public Tproductversion getTproductversion() {
		return this.tproductversion;
	}

	public void setTproductversion(Tproductversion tproductversion) {
		this.tproductversion = tproductversion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idreporter", nullable = false)
	@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
	public Treporter getTreporter() {
		return this.treporter;
	}

	public void setTreporter(Treporter treporter) {
		this.treporter = treporter;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "vocticketstatus", nullable = false)
	@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
	public Tvocabword getVocticketstatus() {
		return this.vocticketstatus;
	}

	public void setVocticketstatus(Tvocabword vocticketstatus) {
		this.vocticketstatus = vocticketstatus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "vocticketresol", nullable = false)
	@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
	public Tvocabword getVocticketresol() {
		return this.vocticketresol;
	}

	public void setVocticketresol(Tvocabword vocticketresol) {
		this.vocticketresol = vocticketresol;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "dateticket", nullable = false, length = 10)
	public Date getDateticket() {
		return this.dateticket;
	}

	public void setDateticket(Date dateticket) {
		this.dateticket = dateticket;
	}

	@Column(name = "externalcodea", length = 60)
	public String getExternalcodea() {
		return this.externalcodea;
	}

	public void setExternalcodea(String externalcodea) {
		this.externalcodea = externalcodea;
	}

	@Column(name = "summary", length = 60)
	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tticket")
	@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
	public Set<Ttickoprodversresol> getTtickoprodversresols() {
		return this.ttickoprodversresols;
	}

	public void setTtickoprodversresols(Set<Ttickoprodversresol> ttickoprodversresols) {
		this.ttickoprodversresols = ttickoprodversresols;
	}

}
