package com.am.entity;
// Generated 20 nov. 2018 18:53:33 by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
/**
 * Tuser generated by hbm2java
 */
@Entity
@Table(name = "tusersignin", catalog = "projectmanagement")
public class Tusersignin implements java.io.Serializable {

	private long idusersignin;
	private String token;
	public String getToken() {
		return token;
	}


	public void setToken(String token) {
		this.token = token;
	}


	


	public void setIdusersignin(long idusersignin) {
		this.idusersignin = idusersignin;
	}


	private Tuser tuser;
	
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "idusersignin", unique = true, nullable = false)
	public long getIdusersignin() {
		return idusersignin;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "iduser")
	@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
	public Tuser getTuser() {
		return this.tuser;
	}


	public void setTuser(Tuser tuser) {
		this.tuser = tuser;
	}


}
