package com.am.entity;
// Generated 20 nov. 2018 18:53:33 by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.core.JsonGenerationException;

/**
 * Tuser generated by hbm2java
 */
@Entity
@Table(name = "tuser", catalog = "projectmanagement")
public class Tuser implements java.io.Serializable {

	private Integer iduser;
	private Tperson tperson;
	private String loginuser;
	private String pwduser;
	private int enableduser;
	@JsonIgnore
	private Set<Tuserrole> tuserroles = new HashSet<Tuserrole>(0);

	public Tuser() {
	}

	public Tuser(Tperson tperson, int enableduser) {
		this.tperson = tperson;
		this.enableduser = enableduser;
	}

	public Tuser(Tperson tperson, String loginuser, String pwduser, int enableduser,	Set<Tuserrole> tuserroles) {
		this.tperson = tperson;
		this.loginuser = loginuser;
		this.pwduser = pwduser;
		this.enableduser = enableduser;
		this.tuserroles = tuserroles;
	}

	@Id
	@Column(name = "iduser", unique = true, nullable = false)
	public Integer getIduser() {
		return this.iduser;
	}

	public void setIduser(Integer iduser) {
		this.iduser = iduser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idperson", nullable = false)
	@JsonIgnore
	public Tperson getTperson() {
		return this.tperson;
	}


	public void setTperson(Tperson tperson) {
		this.tperson = tperson;
	}

	@Column(name = "loginuser", length = 30)
	public String getLoginuser() {
		return this.loginuser;
	}

	public void setLoginuser(String loginuser) {
		this.loginuser = loginuser;
	}

	@Column(name = "pwduser", length = 120)
	public String getPwduser() {
		return this.pwduser;
	}

	public void setPwduser(String pwduser) {
		this.pwduser = pwduser;
	}

	@Column(name = "enableduser", nullable = false)
	public int getEnableduser() {
		return this.enableduser;
	}

	public void setEnableduser(int enableduser) {
		this.enableduser = enableduser;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tuser")
	@JsonIgnore
	public Set<Tuserrole> getTuserroles() {
		return this.tuserroles;
	}

	public void setTuserroles(Set<Tuserrole> tuserroles) {
		this.tuserroles = tuserroles;
	}

}
