// default package
// Generated 11 nov. 2018 20:55:22 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tuser generated by hbm2java
 */
@Entity
@Table(name="tuser"
    ,catalog="projectmanagement"
)
public class Tuser  implements java.io.Serializable {


     private Integer iduser;
     private String loginuser;
     private String pwduser;
     private int enableduser;
     private Integer isreporter;
     private int idperson;

    public Tuser() {
    }

	
    public Tuser(int enableduser, int idperson) {
        this.enableduser = enableduser;
        this.idperson = idperson;
    }
    public Tuser(String loginuser, String pwduser, int enableduser, Integer isreporter, int idperson) {
       this.loginuser = loginuser;
       this.pwduser = pwduser;
       this.enableduser = enableduser;
       this.isreporter = isreporter;
       this.idperson = idperson;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="iduser", unique=true, nullable=false)
    public Integer getIduser() {
        return this.iduser;
    }
    
    public void setIduser(Integer iduser) {
        this.iduser = iduser;
    }

    
    @Column(name="loginuser", length=30)
    public String getLoginuser() {
        return this.loginuser;
    }
    
    public void setLoginuser(String loginuser) {
        this.loginuser = loginuser;
    }

    
    @Column(name="pwduser", length=120)
    public String getPwduser() {
        return this.pwduser;
    }
    
    public void setPwduser(String pwduser) {
        this.pwduser = pwduser;
    }

    
    @Column(name="enableduser", nullable=false)
    public int getEnableduser() {
        return this.enableduser;
    }
    
    public void setEnableduser(int enableduser) {
        this.enableduser = enableduser;
    }

    
    @Column(name="isreporter")
    public Integer getIsreporter() {
        return this.isreporter;
    }
    
    public void setIsreporter(Integer isreporter) {
        this.isreporter = isreporter;
    }

    
    @Column(name="idperson", nullable=false)
    public int getIdperson() {
        return this.idperson;
    }
    
    public void setIdperson(int idperson) {
        this.idperson = idperson;
    }




}


