// default package
// Generated 11 nov. 2018 20:55:22 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tversionproduct generated by hbm2java
 */
@Entity
@Table(name="tversionproduct"
    ,catalog="projectmanagement"
)
public class Tversionproduct  implements java.io.Serializable {


     private int idversionproduct;
     private String nameversion;
     private Date cdateversion;
     private Integer numberversion;
     private Integer enabledversion;
     private Integer idproduct;

    public Tversionproduct() {
    }

	
    public Tversionproduct(int idversionproduct) {
        this.idversionproduct = idversionproduct;
    }
    public Tversionproduct(int idversionproduct, String nameversion, Date cdateversion, Integer numberversion, Integer enabledversion, Integer idproduct) {
       this.idversionproduct = idversionproduct;
       this.nameversion = nameversion;
       this.cdateversion = cdateversion;
       this.numberversion = numberversion;
       this.enabledversion = enabledversion;
       this.idproduct = idproduct;
    }
   
     @Id 

    
    @Column(name="idversionproduct", unique=true, nullable=false)
    public int getIdversionproduct() {
        return this.idversionproduct;
    }
    
    public void setIdversionproduct(int idversionproduct) {
        this.idversionproduct = idversionproduct;
    }

    
    @Column(name="nameversion", length=30)
    public String getNameversion() {
        return this.nameversion;
    }
    
    public void setNameversion(String nameversion) {
        this.nameversion = nameversion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="cdateversion", length=0)
    public Date getCdateversion() {
        return this.cdateversion;
    }
    
    public void setCdateversion(Date cdateversion) {
        this.cdateversion = cdateversion;
    }

    
    @Column(name="numberversion")
    public Integer getNumberversion() {
        return this.numberversion;
    }
    
    public void setNumberversion(Integer numberversion) {
        this.numberversion = numberversion;
    }

    
    @Column(name="enabledversion")
    public Integer getEnabledversion() {
        return this.enabledversion;
    }
    
    public void setEnabledversion(Integer enabledversion) {
        this.enabledversion = enabledversion;
    }

    
    @Column(name="idproduct")
    public Integer getIdproduct() {
        return this.idproduct;
    }
    
    public void setIdproduct(Integer idproduct) {
        this.idproduct = idproduct;
    }




}


