package com.am.entity;
// Generated 20 nov. 2018 18:53:33 by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicUpdate;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Tvocab generated by hbm2java
 */
@Entity
@Table(name = "tvocab", catalog = "projectmanagement")
@DynamicUpdate
//@JsonAutoDetect(fieldVisibility = Visibility.ANY)
public class Tvocab implements java.io.Serializable {

	private Long idvocab;
	private String codevocab;
	private String namevocab;
	private Integer enabledvocab;
	private Integer fixedvocab;
	@JsonIgnore
	private Set<Tvocabword> tvocabwords = new HashSet<Tvocabword>(0);

	public Tvocab() {
	}

	public Tvocab(Long idvocab, String codevocab, String namevocab, Integer enabledvocab, Integer fixedvocab) {
		this.idvocab = idvocab;
		this.codevocab = codevocab;
		this.namevocab = namevocab;
		this.enabledvocab = enabledvocab;
		this.fixedvocab = fixedvocab;
	}

	public Tvocab(Long idvocab, String codevocab, String namevocab, Integer enabledvocab, Integer fixedvocab,
			Set<Tvocabword> tvocabwords) {
		this.idvocab = idvocab;
		this.codevocab = codevocab;
		this.namevocab = namevocab;
		this.enabledvocab = enabledvocab;
		this.fixedvocab = fixedvocab;
		this.tvocabwords = tvocabwords;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "idvocab", unique = true, nullable = false)
	public Long getIdvocab() {
		return this.idvocab;
	}

	public void setIdvocab(Long idvocab) {
		this.idvocab = idvocab;
	}

	@Column(name = "codevocab", nullable = false, length = 30)
	public String getCodevocab() {
		return this.codevocab;
	}

	public void setCodevocab(String codevocab) {
		this.codevocab = codevocab;
	}

	@Column(name = "namevocab", nullable = false, length = 60)
	public String getNamevocab() {
		return this.namevocab;
	}

	public void setNamevocab(String namevocab) {
		this.namevocab = namevocab;
	}

	@Column(name = "enabledvocab", nullable = false)
	public Integer getEnabledvocab() {
		return this.enabledvocab;
	}

	public void setEnabledvocab(Integer enabledvocab) {
		this.enabledvocab = enabledvocab;
	}

	@Column(name = "fixedvocab", nullable = false)
	public Integer getFixedvocab() {
		return this.fixedvocab;
	}

	public void setFixedvocab(Integer fixedvocab) {
		this.fixedvocab = fixedvocab;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tvocab")
	public Set<Tvocabword> getTvocabwords() {
		return this.tvocabwords;
	}

	public void setTvocabwords(Set<Tvocabword> tvocabwords) {
		this.tvocabwords = tvocabwords;
	}

}
