package com.am.entity;
// Generated 20 nov. 2018 18:53:33 by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Tvocab generated by hbm2java
 */
@Entity
@Table(name = "tvocab", catalog = "projectmanagement")
public class Tvocab implements java.io.Serializable {

	private int idvocab;
	private String codevocab;
	private String namevocab;
	private int enabledvocab;
	private int fixedvocab;
	@JsonIgnore
	private Set<Tvocabword> tvocabwords = new HashSet<Tvocabword>(0);

	public Tvocab() {
	}

	public Tvocab(int idvocab, String codevocab, String namevocab, int enabledvocab, int fixedvocab) {
		this.idvocab = idvocab;
		this.codevocab = codevocab;
		this.namevocab = namevocab;
		this.enabledvocab = enabledvocab;
		this.fixedvocab = fixedvocab;
	}

	public Tvocab(int idvocab, String codevocab, String namevocab, int enabledvocab, int fixedvocab,
			Set<Tvocabword> tvocabwords) {
		this.idvocab = idvocab;
		this.codevocab = codevocab;
		this.namevocab = namevocab;
		this.enabledvocab = enabledvocab;
		this.fixedvocab = fixedvocab;
		this.tvocabwords = tvocabwords;
	}

	@Id

	@Column(name = "idvocab", unique = true, nullable = false)
	public int getIdvocab() {
		return this.idvocab;
	}

	public void setIdvocab(int idvocab) {
		this.idvocab = idvocab;
	}

	@Column(name = "codevocab", nullable = false, length = 30)
	public String getCodevocab() {
		return this.codevocab;
	}

	public void setCodevocab(String codevocab) {
		this.codevocab = codevocab;
	}

	@Column(name = "namevocab", nullable = false, length = 60)
	public String getNamevocab() {
		return this.namevocab;
	}

	public void setNamevocab(String namevocab) {
		this.namevocab = namevocab;
	}

	@Column(name = "enabledvocab", nullable = false)
	public int getEnabledvocab() {
		return this.enabledvocab;
	}

	public void setEnabledvocab(int enabledvocab) {
		this.enabledvocab = enabledvocab;
	}

	@Column(name = "fixedvocab", nullable = false)
	public int getFixedvocab() {
		return this.fixedvocab;
	}

	public void setFixedvocab(int fixedvocab) {
		this.fixedvocab = fixedvocab;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tvocab")
	public Set<Tvocabword> getTvocabwords() {
		return this.tvocabwords;
	}

	public void setTvocabwords(Set<Tvocabword> tvocabwords) {
		this.tvocabwords = tvocabwords;
	}

}
