package com.am.entity;
// Generated 20 nov. 2018 18:53:33 by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicUpdate;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Tvocabword generated by hbm2java
 */
@Entity
@Table(name = "tvocabword", catalog = "projectmanagement")
@DynamicUpdate
public class Tvocabword implements java.io.Serializable {

	private Long idvocabword;
	private Tvocab tvocab;
	private String codeword;
	private String icodeword;
	private String nameword;
	private Integer isinternal;
	private Integer enabledvocab;
	private Integer rownumber;
	
	public Tvocabword() {
	}

	public Tvocabword(Long idvocabword, Tvocab tvocab, String codeword, String icodeword, String nameword,
			Integer isinternal, Integer enabledvocab) {
		this.idvocabword = idvocabword;
		this.tvocab = tvocab;
		this.codeword = codeword;
		this.icodeword = icodeword;
		this.nameword = nameword;
		this.isinternal = isinternal;
		this.enabledvocab = enabledvocab;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "idvocabword", unique = true, nullable = false)
	public Long getIdvocabword() {
		return this.idvocabword;
	}

	public void setIdvocabword(Long idvocabword) {
		this.idvocabword = idvocabword;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idvocab", nullable = false)
	@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
	public Tvocab getTvocab() {
		return this.tvocab;
	}

	public void setTvocab(Tvocab tvocab) {
		this.tvocab = tvocab;
	}

	@Column(name = "codeword", nullable = false, length = 30)
	public String getCodeword() {
		return this.codeword;
	}

	public void setCodeword(String codeword) {
		this.codeword = codeword;
	}

	@Column(name = "icodeword", nullable = false, length = 30)
	public String getIcodeword() {
		return this.icodeword;
	}

	public void setIcodeword(String icodeword) {
		this.icodeword = icodeword;
	}

	@Column(name = "nameword", nullable = false, length = 60)
	public String getNameword() {
		return this.nameword;
	}

	public void setNameword(String nameword) {
		this.nameword = nameword;
	}

	@Column(name = "isinternal", nullable = false)
	public Integer getIsinternal() {
		return this.isinternal;
	}

	public void setIsinternal(Integer isinternal) {
		this.isinternal = isinternal;
	}

	@Column(name = "enabledvocab", nullable = false)
	public Integer getEnabledvocab() {
		return this.enabledvocab;
	}

	public void setEnabledvocab(Integer enabledvocab) {
		this.enabledvocab = enabledvocab;
	}

	@Column(name = "rownumber")
	public Integer getRownumber() {
		return this.rownumber;
	}

	public void setRownumber(Integer rownumber) {
		this.rownumber = rownumber;
	}
}
